# Generated by Django 2.0 on 2018-06-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Alternative name')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Criteria name')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Criteria rank')),
                ('weight', models.IntegerField(verbose_name='Criteria weight')),
                ('criteria_type', models.CharField(choices=[('ql', 'Qualitative'), ('qn', 'Quantitative')], max_length=2, verbose_name='Criteria type')),
                ('optimal_type', models.CharField(blank=True, choices=[('min', 'Minimum'), ('max', 'Maximum')], max_length=3, null=True, verbose_name='Optimal criteria type')),
                ('measure', models.CharField(max_length=255, verbose_name='Criteria measure')),
                ('scale_type', models.CharField(max_length=255, verbose_name='Criteria scale type')),
            ],
            options={
                'verbose_name_plural': 'Criterias',
                'ordering': ['rank', 'weight', 'name'],
                'verbose_name': 'Criteria',
            },
        ),
        migrations.CreateModel(
            name='LPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='LPR name')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='LPR rank')),
            ],
            options={
                'verbose_name_plural': 'LPR',
                'ordering': ['rank', 'name'],
                'verbose_name': 'LPR',
            },
        ),
        migrations.CreateModel(
            name='LPRCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(max_length=2, null=True)),
                ('master_lpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_lpr', to='decisions.LPR', verbose_name='Master LPR')),
                ('target_lpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_lpr', to='decisions.LPR', verbose_name='Target LPR')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mark name')),
                ('rank', models.IntegerField(verbose_name='Mark rank')),
                ('numeric_value', models.IntegerField(verbose_name='Mark numeric equivalent')),
                ('normalized_mark', models.IntegerField(blank=True, null=True, verbose_name='Normalized mark')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Criteria', verbose_name='Criteria')),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'ordering': ['rank', 'name'],
                'verbose_name': 'Mark',
            },
        ),
        migrations.CreateModel(
            name='PairCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=2, null=True)),
                ('first_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_alternative', to='decisions.Alternative', verbose_name='First alternative')),
                ('lpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.LPR', verbose_name='LPR')),
                ('second_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_alternative', to='decisions.Alternative', verbose_name='Second alternative')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Result rank')),
                ('alternative_weight', models.IntegerField(verbose_name='Alternative weight')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Alternative', verbose_name='Alternative')),
                ('lpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.LPR', verbose_name='LPR')),
            ],
            options={
                'verbose_name_plural': 'Results',
                'ordering': ['rank', 'alternative_weight'],
                'verbose_name': 'Result',
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Alternative', verbose_name='Alternative')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.Mark', verbose_name='Mark')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='vectors',
            field=models.ManyToManyField(through='decisions.Vector', to='decisions.Alternative', verbose_name='Vectors'),
        ),
        migrations.AddField(
            model_name='lpr',
            name='results',
            field=models.ManyToManyField(through='decisions.Result', to='decisions.Alternative', verbose_name='Results'),
        ),
    ]
